<?php

/**
 * @file
 * Installation/Uninstallation hooks.
 */

/**
 * Implements hook_uninstall().
 */
function islandora_simple_map_kml_uninstall() {
  $variables = array(
    'islandora_simple_map_kml_mimetypes',
    'islandora_simple_map_kml_dsids',
    'islandora_simple_map_kml_models',
    'islandora_simple_map_kml_mods_xpaths',
    'islandora_simple_map_kml_ddi_xpaths',
  );
  array_map('variable_del', $variables);
}
