sudo: required
language: php
php:
  - 5.3.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
branches:
  only:
    - /^7.x/
env:
  matrix:
    - FEDORA_VERSION="3.5"
    - FEDORA_VERSION="3.6.2"
    - FEDORA_VERSION="3.7.0"
    - FEDORA_VERSION="3.8.1"
before_install:
  - cd $HOME
  - git clone -b 7.x git://github.com/Islandora/islandora.git
  - export ISLANDORA_DIR=$HOME/islandora
  - $ISLANDORA_DIR/tests/scripts/travis_setup.sh
  - cd $HOME/drupal-*
  - ln -s $TRAVIS_BUILD_DIR sites/all/modules/islandora_simple_map
  - drush en --user=1 --yes islandora_simple_map
before_script:
  # Mysql might time out for long tests, increase the wait timeout.
  - mysql -e 'SET @@GLOBAL.wait_timeout=1200'

script:
  - $TRAVIS_BUILD_DIR/tests/scripts/line_endings.sh sites/all/modules/islandora_simple_map
  - drush coder-review --reviews=production,security,style,i18n,potx,sniffer islandora_simple_map
  - phpcpd --names *.module,*.inc,*.test sites/all/modules/islandora_simple_map
  - php scripts/run-tests.sh --php `phpenv which php` --url http://localhost:8081 --verbose "Islandora Simple Map"
