<?php

/**
 * @file
 * This file contains all install related hooks.
 */

/**
 * Implements hook_uninstall().
 */
function islandora_simple_map_uninstall() {
  $variables = array(
    'islandora_simple_map_xpath',
    'islandora_simple_map_iframe_width',
    'islandora_simple_map_iframe_height',
    'islandora_simple_map_zoom',
    'islandora_simple_map_collapsed',
    'islandora_simple_map_google_api_key',
  );
  array_walk($variables, 'variable_del');
}
