<?php
/**
 * @file
 * General hooks.
 */

const ISLANDORA_SIMPLE_MAP_DDI_COORDS_REGEX = '/^[+\-]?\d+\.\d+?/';

/**
 * Implements hook_menu().
 */
function islandora_simple_map_ddi_menu() {
  $items = array();

  $items['admin/islandora/tools/islandora_simple_map/scrape_ddi'] = array(
    'title' => 'DDI scraping',
    'description' => 'Configure the DDI scraping settings.',
    'page callback' => 'drupal_get_form',
    'access arguments' => array('administer site configuration'),
    'page arguments' => array('islandora_simple_map_ddi_admin_settings_form'),
    'type' => MENU_LOCAL_TASK,
    'file' => 'includes/admin_form.inc',
    'weight' => 10,
  );

  return $items;
}
