<?php
/**
 * @file
 * General hooks.
 */

const SCRAPE_MODS_KML_XPATHS = "//mods:subject/mods:cartographics/mods:cartographicExtension/*[local-name() = 'kml']";
const SCRAPE_MODS_COORDS_REGEX = '/^[+\-]?\d+\.\d+,\s*[+\-]?\d+\.\d+?/';

/**
 * Implements hook_menu().
 */
function islandora_simple_map_scrape_mods_menu() {
  $items = array();
  $items['admin/islandora/tools/islandora_simple_map/scrape_mods'] = array(
    'title' => 'MODS scraping',
    'description' => 'Configure the MODS scraping settings.',
    'page callback' => 'drupal_get_form',
    'access arguments' => array('administer site configuration'),
    'page arguments' => array('islandora_simple_map_scrape_mods_admin_settings_form'),
    'type' => MENU_LOCAL_TASK,
    'file' => 'includes/admin_form.inc',
    'weight' => 10,
  );

  $items['islandora/object/%islandora_object/datastream/%islandora_datastream/islandora_simple_map_scrape_mods_kml'] = array(
    'title' => 'Scrape MODS KML',
    'page callback' => '_islandora_simple_map_scrape_mods_kml',
    'page arguments' => array(4, 6),
    'access callback' => '_islandora_simple_map_scrape_mods_kml_access_callback',
    'access arguments' => array(4),
    'type' => MENU_CALLBACK,
    'file' => 'includes/scrape_kml.inc',
  );

  return $items;
}

/**
 * Access callback for the KML scrape callback.
 */
function _islandora_simple_map_scrape_mods_kml_access_callback($datastream) {
  return $datastream->id == 'MODS' && islandora_datastream_access(ISLANDORA_VIEW_OBJECTS, $datastream);
}

/**
 * Implements hook_islandora_simple_map_get_kml().
 */
function islandora_simple_map_scrape_mods_islandora_simple_map_get_kml(AbstractObject $object) {
  module_load_include('inc', 'islandora_simple_map_scrape_mods', 'includes/utilities');
  $xpaths = _islandora_simple_map_scrape_mods_parse_paths(variable_get('islandora_simple_map_scrape_mods_kml_xpaths', SCRAPE_MODS_KML_XPATHS));

  $get_value = function (DOMNode $node, $pos) use ($object) {
    return url("islandora/object/{$object->id}/datastream/MODS/islandora_simple_map_scrape_mods_kml/$pos/loc.kml", array(
      'absolute' => TRUE,
    ));
  };
  $kml = array();
  foreach (_islandora_simple_map_scrape_mods_scrape($object, $xpaths) as $pos => $node) {
    $kml[] = $get_value($node, $pos);
  }
  return $kml;
}
