<?php
/**
 * @file
 * General hooks.
 */

const SCRAPE_MODS_KML_XPATHS = "//mods:subject/mods:cartographics/mods:cartographicExtension/*[local-name() = 'kml']";
const SCRAPE_MODS_COORDS_REGEX = '/^[+\-]?\d+\.\d+,\s*[+\-]?\d+\.\d+?/';
/**
 * Implements hook_islandora_simple_map_get_kml().
 */
function islandora_simple_map_scrape_mods_islandora_simple_map_get_kml(AbstractObject $object) {
  module_load_include('inc', 'islandora_simple_map_scrape_mods', 'includes/utilities');
  $xpaths = _islandora_simple_map_scrape_mods_parse_paths(variable_get('islandora_simple_map_scrape_mods_kml_xpaths', SCRAPE_MODS_KML_XPATHS));

  $get_value = function (DOMNode $node, $pos) use ($object) {
    return url("islandora/object/{$object->id}/datastream/MODS/islandora_simple_map_scrape_mods_kml/$pos/loc.kml", array(
      'absolute' => TRUE,
    ));
  };
  $kml = array();
  foreach (_islandora_simple_map_scrape_mods_scrape($object, $xpaths) as $pos => $node) {
    $kml[] = $get_value($node, $pos);
  }
  return $kml;
}
